#!/bin/sh

# Remap some keys.
[[ -f "${XDG_CONFIG_HOME}/X11/xmodmap/xmodmaprc" ]] && xmodmap "${XDG_CONFIG_HOME}/X11/xmodmap/xmodmaprc"

#
# Dynamic window manager.
#
# Start suckless status monitor.
slstatus &
# Start xss-lock to trigger slock.
xss-lock -- slock &
# Start suckless terminal.
st &
# Start firefox.
firefox &
# Start dynamic window manager.
exec dwm
