#!/bin/bash

# Remap some keys.
# map_file="${HOME}/.config/X11/xmodmaprc"
# test -f "${map_file}" && /usr/bin/xmodmap "${map_file}"
# unset map_file

# xkbcomp
# TODO: Separate custom mappings.
# See https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Enabling_mouse_keys
map_file="${HOME}/.config/X11/xkeymap.xkb"
test -f "${map_file}" && /usr/bin/xkbcomp "${map_file}" "${DISPLAY}"
unset map_file

#
# Start a window manager and other things.
#
# Suckless status monitor.
/usr/bin/slstatus &

# Locker trigger.
/usr/bin/xss-lock -- /usr/bin/slock &

# Suckless terminal.
/usr/bin/st &

# Transmission daemon
/usr/bin/transmission-daemon

# Firefox browser.
/usr/bin/firefox &

# Start dynamic window manager.
exec /usr/bin/dwm

# vim: ft=sh
