#!/bin/bash

# Taken from /etc/X11/xinit/xinitrc
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#
# Start a window manager and other things.
#
# Suckless status monitor.
/usr/bin/slstatus &

# Locker trigger.
/usr/bin/xss-lock -- /usr/bin/slock &

# Suckless terminal.
/usr/bin/st &

# Firefox browser.
/usr/bin/firefox &

# Start dynamic window manager.
exec /usr/bin/dwm

# vim: ft=sh

