#!/bin/bash

## Source: Arch Wiki.
#export LESS_TERMCAP_mb=$'\E[1;31m'     # begin blink, red
#export LESS_TERMCAP_md=$'\E[1;36m'     # begin bold, cyan
#export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
#export LESS_TERMCAP_so=$'\E[01;44;33m' # begin reverse video, yellow on blue
#export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
#export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline, green
#export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

#export LESS_TERMCAP_mb=$(tput blink; tput setaf 2)              # begin blink, green
#export LESS_TERMCAP_md=$(tput bold; tput setaf 6)               # begin bold, cyan
#export LESS_TERMCAP_me=$(tput sgr0)                             # reset bold/blink
#export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4) # begin reverse video, yellow on red ???
#export LESS_TERMCAP_se=$(tput rmso; tput sgr0)                  # reset reverse video
##export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 7)    # begin underline, white
#export LESS_TERMCAP_us=$(tput smul;)                            # begin underline
#export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)                  # reset underline
#export LESS_TERMCAP_mr=$(tput rev)
#export LESS_TERMCAP_mh=$(tput dim)
#export LESS_TERMCAP_ZN=$(tput ssubm)
#export LESS_TERMCAP_ZV=$(tput rsubm)
#export LESS_TERMCAP_ZO=$(tput ssupm)
#export LESS_TERMCAP_ZW=$(tput rsupm)
#export GROFF_NO_SGR=1 # For Konsole and Gnome-terminal
