#!/bin/sh

# Everything is in terminfo manpage.
# Color       #define       Value       RGB
# black     COLOR_BLACK       0     0, 0, 0
# red       COLOR_RED         1     max,0,0
# green     COLOR_GREEN       2     0,max,0
# yellow    COLOR_YELLOW      3     max,max,0
# blue      COLOR_BLUE        4     0,0,max
# magenta   COLOR_MAGENTA     5     max,0,max
# cyan      COLOR_CYAN        6     0,max,max
# white     COLOR_WHITE       7     max,max,max
# FG - BG: red - blue, yellow - cyan.
# Bold for headings, command synopses, and code font.
# Underline for proper names, variable names, and type names in some manpages.
# Inverse for the prompt at the bottom.
export LESS_TERMCAP_us="$(tput setaf 6)"            # start underline, cyan
export LESS_TERMCAP_ue="$(tput sgr0)"               # reset underline
